kind: pipeline
name: default

steps:
- name: trigger  
  image: plugins/downstream
  settings:
    server: https://zkopru.sifnoc.net
    token:
      from_secret: drone_token
    repositories:
      - sifnoc/stress-test@feat/drone-ci
