kind: pipeline
name: default

clone:
  disable: true

steps:
- name: trigger  
  image: plugins/downstream
  settings:
    server: https://drone.zkopru.network
    fork: false
    token:
      from_secret: drone_token
    params:
      - TRIGGER_HASH=${DRONE_COMMIT}
      - TRIGGER_BRANCH=${DRONE_BRANCH}
    repositories:
      - zkopru-network/stress-test

trigger:
  branch:
    - main
