kind: pipeline
name: default

clone:
  disable: true

steps:
- name: trigger  
  image: plugins/downstream
  fork: true
  settings:
    server: https://drone.zkopru.net
    token:
      from_secret: drone_token
    repositories:
      - zkopru-network/stress-test

trigger:
  branch:
    - main
