version: '3'

services:
  testnet-geth:
    build:
      context: ./packages/contracts/
      dockerfile: ../../dockerfiles/Contract.geth.dockerfile
    ports:
      - '5000:5000'
    networks:
      default:
        ipv4_address: 172.30.1.2
        aliases: 
          - testnet
    command: >
      sh -c "set -x &&
      geth init --datadir data genesis.json &&
      geth account import testnet-key --password testnet-pass --datadir data &&
      geth --dev --dev.period 14 --maxpeers 0 --fakepow --mine --miner.gasprice 1 --miner.threads 2 --miner.gastarget 12000000 --networkid 20200406 --datadir data --http --http.addr 0.0.0.0 --http.port 5000 --http.vhosts '*' --http.corsdomain '*' --rpc.allow-unprotected-txs --http.api eth,net,web3,debug,personal,miner --ws --ws.addr 0.0.0.0 --ws.port 5000 --ws.api eth,net,web3,debug,personal --ws.rpcprefix '/' --ws.origins '*' --unlock 90f8bf6a479f320ead074411a4b0e7944ea8c9c1 --password testnet-pass --allow-insecure-unlock &
      sleep 10 &&
      truffle migrate --network testnet  &&
      nc -w 10 coordinator 5354 &&
      tail -f /dev/null"
  coordinator:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    ports:
      - '8888:8888'
    networks:
      default:
        ipv4_address: 172.30.1.3
        aliases:
          - coordinator
    depends_on:
      - 'testnet-geth'
    environment:
      - TARGET_HOST=testnet
      - COORDINATOR_IP=172.30.1.3
    command: >
      bash -c "nc -l -p 5354 &&
      node /proj/packages/generator/dist/coordinator.js"
  organizer:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    ports:
      - '8080:8080'
    volumes:
      - './packages:/proj/packages'
    depends_on:
      - 'coordinator'
    environment:
      - DEFAULT_COORDINATOR=http://172.30.1.3:8888
    command: bash -c "node /proj/packages/generator/dist/organizer.js"
  wallet:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    environment:
      - DEFAULT_COORDINATOR=http://172.30.1.3:8888
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - './packages:/proj/packages'
    depends_on:
      - 'organizer'
    command: > 
      bash -c "sleep 10 && node /proj/packages/generator/dist/wallet.js"
  turner:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    environment:
      - DEFAULT_COORDINATOR=http://172.30.1.3:8888
    volumes:
      - './packages:/proj/packages'
    depends_on:
      - 'wallet'
    command: bash -c "sleep 60 && node /proj/packages/generator/dist/blockturner.js"

networks:
  default:
    ipam:
      config:
        - subnet: 172.30.1.0/24
