version: '3'

services:
  deployed-geth:
    ports:
      - '8545:8545'
    build:
      context: ./packages/contracts/
      dockerfile: ../../dockerfiles/Contract.geth.dockerfile
    command: >
      geth init --datadir data &&
      geth account import testnet-key --password testnet-pass --datadir data &&
      geth import-preimage --datadir data zkopru_geth.db &&
      geth --maxpeers 0 --fakepow --mine --miner.gasprice 1 --miner.threads 1 --miner.gastarget 12000000 --networkid 20200406 --datadir data --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" --http.api eth,net,web3,personal,miner --nousb
  testnet:
    ports:
      - '5000:5000'
    build:
      context: ./packages/contracts/
      dockerfile: ../../dockerfiles/Contract.dockerfile
    environment:
      TARGET_HOST: 'deployed-geth'
      BLOCKTIME: 10000
    command: >
      sh -c "sh wait_deploy_contracts.sh &&
      npx hardhat node --port 5000 &
      echo 'Ready teatchain forked zkopru contract deployed geth node.' &&
      echo "Done" | nc -w0 coordinator 5354 &&
      echo "Done" | nc -w0 wallet 5354 &&
      tail -f /dev/null"
  coordinator:
    build:
      context: ./
      dockerfile: ./dockerfiles/Cli.dockerfile
    ports:
      - '1234:1234'
      - '8888:8888'
    links:
      - 'testnet:testnet'
    depends_on:
      - 'testnet'
    environment:
      TARGET_HOST: 'testnet'
      PORT: 1234
    command: >
      bash -c "nc -l -p 5354 &&
      bash wait_deploy_contracts.sh &&
      gotty -w --port 1234 node /proj/packages/cli/dist/apps/coordinator/cli.js --config /proj/packages/cli/coordinator.dev.json"
  wallet:
    build:
      context: ./
      dockerfile: ./dockerfiles/Cli.dockerfile
    ports:
      - '4321:4321'
    links:
      - 'testnet:testnet'
      - 'coordinator:coordinator'
    depends_on:
      - 'testnet'
    environment:
      TARGET_HOST: 'testnet'
      PORT: 4321
    command: >
      bash -c "nc -l -p 5354  &&
      bash wait_deploy_contracts.sh &&
      gotty -w --port 4321 node /proj/packages/cli/dist/apps/wallet/cli.js --config /proj/packages/cli/wallet.dev.json"
