version: '3'

services:
  testnet:
    ports:
      - '5000:5000'
    build:
      context: ./packages/contracts/
      dockerfile: ../../dockerfiles/Contract.dockerfile
    networks:
      default:
        ipv4_address: 172.30.1.2
    command: ganache-cli --db=/data -i 20200406 -p 5000 --gasLimit 12000000 --deterministic --host 0.0.0.0 --secure --blockTime 10
  coordinator:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    ports:
      - '8888:8888'
    links:
      - 'testnet'
    networks:
      default:
        ipv4_address: 172.30.1.3
    depends_on:
      - 'testnet'
    command: bash -c "sleep 5 && node /proj/packages/generator/dist/coordinator.js"
  redis:
    image: redis
    ports:
      - '6379:6379'
  organizer:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    links:
      - 'testnet'
      - 'coordinator'
      - 'wallet'
    ports:
      - '8080:8080'
    depends_on:
      - 'wallet'
    command: bash -c "sleep 10 && node /proj/packages/generator/dist/organizer.js"
  wallet:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    links:
      - 'testnet'
      - 'coordinator'
    environment:
      - DEFAULT_COORDINATOR=http://172.30.1.3:8888
    depends_on:
      - 'coordinator'
    command: bash -c "sleep 15 && node /proj/packages/generator/dist/wallet.js"

networks:
  default:
    ipam:
      config:
        - subnet: 172.30.1.0/24
