version: '3'

services:
  testnet-geth:
    build:
      context: ./packages/contracts/
      dockerfile: ../../dockerfiles/Contract.geth.dockerfile
    ports:
      - '5000:5000'
    networks:
      default:
        ipv4_address: 172.100.1.4
        aliases: 
          - testnet
    command: sh /proj/run_geth.sh
  coordinator:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    ports:
      - '8888:8888'
    networks:
      default:
        ipv4_address: 172.100.1.5
        aliases:
          - coordinator
    volumes:
      - './packages:/proj/packages'
    depends_on:
      - 'testnet-geth'
    command: >
      bash -c "nc -l -p 5354 &&
      node /proj/packages/generator/dist/coordinator.js"
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      default:
        ipv4_address: 172.100.1.6
  organizer:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    ports:
      - '8080:8080'
    volumes:
      - './packages:/proj/packages'
    networks:
      default:
        ipv4_address: 172.100.1.7
    depends_on:
      - 'redis'
      - 'coordinator'
    command: bash -c "node /proj/packages/generator/dist/organizer.js"
  wallet:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    volumes:
      - './packages:/proj/packages'
    depends_on:
      - 'redis'
      - 'organizer'
    command: > 
      bash -c "sleep 10 && node /proj/packages/generator/dist/wallet.js"
  turner:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    volumes:
      - './packages:/proj/packages'
    depends_on:
      - 'wallet'
    command: bash -c "sleep 60 && node /proj/packages/generator/dist/blockturner.js"

networks:
  default:
    ipam:
      config:
        - subnet: 172.100.1.0/24
