version: '3'

services:
  testnet-scratch:
    ports:
      - '5000:5000'
    build:
      context: ./packages/contracts/
      dockerfile: ../../dockerfiles/Contract.dockerfile
    environment:
      BLOCKTIME: 10000
    command: >
      sh -c "npx hardhat node --hostname 0.0.0.0 --port 5000 &
      sleep 5 &&
      truffle migrate --network testnet &&
      echo 'Finished Zkopru contract deployment.' &&
      echo "Done" | nc -w0 coordinator 5354 &&
      echo "Done" | nc -w0 wallet 5354 &&
      tail -f /dev/null"
  coordinator:
    build:
      context: ./
      dockerfile: ./dockerfiles/Cli.dockerfile
    ports:
      - '1234:1234'
      - '8888:8888'
    links:
      - 'testnet-scratch:testnet'
    depends_on:
      - 'testnet-scratch'
    environment:
      TARGET_HOST: 'testnet'
      PORT: 1234
    command: >
      bash -c "nc -l -p 5354 &&
      bash wait_deploy_contracts.sh &&
      gotty -w --port 1234 node /proj/packages/cli/dist/apps/coordinator/cli.js --config /proj/packages/cli/coordinator.dev.json"
  wallet:
    build:
      context: ./
      dockerfile: ./dockerfiles/Cli.dockerfile
    ports:
      - '4321:4321'
    links:
      - 'testnet-scratch:testnet'
      - 'coordinator:coordinator'
    depends_on:
      - 'testnet-scratch'
    environment:
      TARGET_HOST: 'testnet'
      PORT: 4321
    command: >
      bash -c "nc -l -p 5354  &&
      bash wait_deploy_contracts.sh &&
      gotty -w --port 4321 node /proj/packages/cli/dist/apps/wallet/cli.js --config /proj/packages/cli/wallet.dev.json"
