version: '3'

services:
  testnet:
    ports:
      - '8545:8545'
    build:
      context: ./packages/contracts/
      dockerfile: ../../dockerfiles/Contract.geth.dockerfile
    ports:
      - '5000:5000'
    command: >
      geth init --datadir data genesis.json &&
      geth account import testnet-key --password testnet-pass --datadir data &&
      geth --maxpeers 0 --fakepow --mine --miner.gasprice 1 --miner.threads 1 --miner.gastarget 12000000 --networkid 20200406 --datadir data --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" --rpc.allow-unprotected-txs --http.api eth,net,web3,personal,miner --nousb &
      truffle migrate --network develop  && sleep 1 && tail -f /dev/null
  coordinator:
    build:
      context: ./
      dockerfile: ./dockerfiles/Cli.dockerfile
    ports:
      - '8888:8888'
    links:
      - 'testnet:testnet'
    depends_on:
      - 'testnet'
    environment:
      TARGET_HOST: 'testnet'
    command: >
      bash -c "nc -l -p 5354 &&
      bash wait_deploy_contracts.sh &&
      node /proj/packages/coordinator/dist/cli.js --ws ws://testnet:5000 --config /proj/packages/coordinator/coordinator.json"
