version: '3'

services:
  testnet:
    build:
      context: ./packages/contracts/
      dockerfile: ../../dockerfiles/Contract.dockerfile
    ports:
      - '5000:5000'
    command: >
      sh -c "npx hardhat node --hostname 0.0.0.0 --port 5000 &
      sleep 5 &&
      truffle migrate --network testnet &&
      echo 'Finished Zkopru contract deployment.' &&
      echo "Done" | nc -w0 coordinator 5354 &&
      tail -f /dev/null"
  coordinator:
    build:
      context: ./
      dockerfile: ./dockerfiles/Coordinator.dockerfile
    ports:
      - '8888:8888'
    links:
      - 'testnet:testnet'
    depends_on:
      - 'testnet'
    environment:
      TARGET_HOST: 'testnet'
    command: >
      bash -c "nc -l -p 5354 &&
      bash wait_deploy_contracts.sh &&
      node /proj/packages/coordinator/dist/cli.js --ws ws://testnet:5000 --config /proj/packages/coordinator/coordinator.json"
