version: "3"

services:
  testnet:
    ports:
      - "5000:5000"
    build:
      context: ./packages/contracts/
      dockerfile: ../../dockerfiles/Contract.dockerfile
    command: ganache-cli --db=/data -i 20200406 -p 5000 --gasLimit 12000000 --deterministic --host 0.0.0.0 --secure --blockTime 10
  coordinator:
    build:
      context: ./
      dockerfile: ./dockerfiles/Cli.dockerfile
    ports:
      - "1234:1234"
      - "8888:8888"
    depends_on:
      - 'testnet'
      - 'postgres'
    environment:
      PORT: 1234
      POSTGRES_URL: postgresql://postgres:helloworld@postgres:5432/zkopru
  wallet:
    build:
      context: ./
      dockerfile: ./dockerfiles/Cli.dockerfile
    ports:
      - "4321:4321"
    depends_on:
      - 'testnet'
      - 'postgres'
    environment:
      PORT: 4321
      SKIP_MIGRATE: 1
      POSTGRES_URL: postgresql://postgres:helloworld@postgres:5432/zkopru
