version: 2.1
workflows:
  test_app:
    jobs:
      - build
      # - lint:
      #     requires:
      #       - build
      - load_keys:
          requires:
            - build
      # - test_circuits:
      #     requires:
      #       - build_keys
      # - test_coordinator:
      #     requires:
      #       - build
      # - test_accounts:
      #     requires:
      #       - build
      # - test_tree:
      #     requires:
      #       - build
      # - test_babyjubjub:
      #     requires:
      #       - build
      # - test_client:
      #     requires:
      #       - build
      - test_database:
          requires:
            - build
      - test_zkwizard:
          requires:
            - load_keys
      - test_integration:
          requires:
            - load_keys
      # - test_utils:
      #     requires:
      #       - build
      - test_cli:
          requires:
            - build
jobs:
  build:
    docker:
      - image: cimg/node:12.22.0
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Install
          command: yarn
      - run:
          name: Build TS
          command: yarn build:ts:serial
      - persist_to_workspace:
          root: ~/
          paths: project
  lint:
    docker:
      - image: cimg/node:12.22.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint
          command: yarn lint .
  load_keys:
    docker:
      - image: cimg/node:12.22.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Load Keys
          command: |
            cd packages/circuits
            yarn download-keys
      - persist_to_workspace:
          root: ~/
          paths: project
  test_circuits:
    docker:
      - image: cimg/node:12.22.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Circuit Tests
          command: yarn test --scope=@zkopru/circuits
          no_output_timeout: 120m
  test_coordinator:
    docker:
      - image: cimg/node:12.22.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Coordinator Tests
          command: |
            cd packages/coordinator
            yarn test
  test_contracts:
    docker:
      - image: cimg/node:12.22.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Generate Block Data
          command: |
            cd packages/contracts
            DEBUG=1 yarn testblock:generate --scope=@zkopru/contracts
      - run:
          name: Contract Tests
          command: yarn test --scope=@zkopru/contracts
  test_accounts:
    docker:
      - image: cimg/node:12.22.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Account Tests
          command: yarn test --scope=@zkopru/account
  test_tree:
    docker:
      - image: cimg/node:12.22.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Tree Tests
          command: yarn test --scope=@zkopru/tree
  test_zkwizard:
    docker:
      - image: cimg/node:12.22.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: ZK Wizard Tests
          command: yarn test --scope=@zkopru/zk-wizard
  test_client:
    docker:
      - image: cimg/node:12.22.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Client Tests
          command: |
            cd packages/client
            yarn test
  test_database:
    docker:
      - image: cimg/node:12.22.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Database Tests
          command: yarn test --scope=@zkopru/database
  test_babyjubjub:
    docker:
      - image: cimg/node:12.22.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: BabyJubJub Tests
          command: yarn test --scope=@zkopru/babyjubjub
  test_utils:
    docker:
      - image: cimg/node:12.22.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Utils Tests
          command: yarn test --scope=@zkopru/utils
  test_integration:
    docker:
      - image: cimg/node:12.22.0 
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Integration Tests
          command: |
            cd packages/integration-test
            LOG_LEVEL=debug yarn test
  test_cli:
    docker:
      - image: cimg/node:12.22.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Cli Tests
          command: |
            cd packages/cli
            yarn test
