// import fs from 'fs'
import BN from 'bn.js'
import { toWei } from 'web3-utils'
import fetch from 'node-fetch'

import { Fp } from '@zkopru/babyjubjub'
import { DB } from '@zkopru/database'
import { UtxoStatus, Utxo, Sum } from '@zkopru/transaction'
import { HDWallet, ZkAccount } from '@zkopru/account'
import { logger, sleep } from '@zkopru/utils'
import { ZkWalletAccount, ZkWalletAccountConfig } from '@zkopru/zk-wizard'
import { TestTxBuilder } from './testbuilder'
import { jsonToZkTx, logAll } from './generator-utils'

// TODO : extends to other type of assets
export type noteAmount = { eth: string; fee: string }

export interface GeneratorConfig {
  db: DB
  hdWallet: HDWallet
  account: ZkAccount
  noteAmount?: noteAmount
  weiPrice?: string
  ID?: number
}

//* * Only ETH transafer zkTx generator as 1 inflow 2 outflows */
export class TransferGenerator extends ZkWalletAccount {
  ID: number

  isActive: boolean

  noteAmount: noteAmount

  unspentUTXO: Utxo[]

  usedUtxoSalt: Set<number>

  weiPrice: string

  worker: Worker | undefined

  lastSalt: Fp

  usePreZkTx: boolean

  constructor(config: ZkWalletAccountConfig & GeneratorConfig) {
    super(config)
    this.ID = config.ID ?? Math.floor(Math.random() * 10000) // TODO : It seems only need in docker environment
    this.isActive = false
    this.noteAmount = config.noteAmount ?? {
      eth: toWei('0.1'),
      fee: toWei('0.01'),
    }
    this.unspentUTXO = []
    this.usedUtxoSalt = new Set([])
    this.weiPrice = config.weiPrice ?? toWei('2000', 'gwei')
    this.usePreZkTx = false

    /**  
     * Starting with Ether Note generated by deposit tx, It has 1 as salt
    
    the salt will be using a sequence for mass transaction in layer 2 as testing
     
         2 - 4 ...
       /   \  
     1       5 ...
       \     
         3 - 6 ...
           \
             7 ...
    */
    this.lastSalt = Fp.from(1)
  }

  async startGenerator() {
    if (!this.node.isRunning()) {
      this.node.start()
    }

    try {
      const result = await this.depositEther(
        toWei('50'),
        this.noteAmount.fee,
        this.account?.zkAddress,
        this.lastSalt,
      )
      if (!result) {
        throw new Error(' Deposit Transaction Failed!')
      } else {
        logger.info(`Deposit Tx sent`)
      }
    } catch (err) {
      logger.error(err)
    }

    while (!this.isActive) {
      await sleep(1000)
      const stagedDeposit = await this.node.layer1.upstream.methods
        .stagedDeposits()
        .call()
      if (parseInt(stagedDeposit.merged, 10) === 0) {
        this.isActive = true
        fetch(`http://organizer:8080/register`, {
          method: 'post',
          body: JSON.stringify({
            ID: this.ID,
            address: this.account?.ethAddress,
          }),
        })
        logger.info(`First Deposit Tx is processed`)
      }
    }

    while (this.isActive) {
      this.unspentUTXO = await this.getUtxos(this.account, UtxoStatus.UNSPENT)

      if (this.unspentUTXO.length === 0) {
        logger.info('No Spendable Utxo, wait until available')
        await sleep(10000)
        continue
      }

      // All transaction are self transaction with same amount, only unique things is salt.
      let sendableUtxo: Utxo | undefined

      for (const utxo of this.unspentUTXO) {
        let isUsedUtxo = false
        if (this.usedUtxoSalt.has(utxo.salt.toNumber())) {
          isUsedUtxo = true
        }
        if (!isUsedUtxo) {
          sendableUtxo = utxo
          break
        }
      }

      // TODO : Create Tx then goto queue
      // TODO : not using flag, then goto check how many pre-generated utxo are available..
      if (sendableUtxo && this.usePreZkTx) {
        const { tx, zkTx } = jsonToZkTx(
          `./packages/generator/zktx/${this.ID}/${sendableUtxo.salt}.json`,
        )

        try {
          // TODO : check private method in ZkWalletAccount class
          tx.outflow.forEach(async outflow => {
            await this.db.create('Utxo', {
              hash: outflow
                .hash()
                .toUint256()
                .toString(),
              owner: outflow.owner.toString(),
              salt: outflow.salt.toUint256().toString(),
              eth: outflow
                .eth()
                .toUint256()
                .toString(),
              tokenAddr: outflow
                .tokenAddr()
                .toAddress()
                .toString(),
              erc20Amount: outflow
                .erc20Amount()
                .toUint256()
                .toString(),
              nft: outflow
                .nft()
                .toUint256()
                .toString(),
              status: UtxoStatus.NON_INCLUDED,
            })
          })
          this.lockUtxos(tx.inflow)
          await this.sendLayer2Tx(zkTx)
          this.usedUtxoSalt.add(sendableUtxo.salt.toNumber())
        } catch (err) {
          logger.error(err)
        }
      } else if (sendableUtxo && !this.usePreZkTx) {
        const testTxBuilder = new TestTxBuilder(this.account?.zkAddress!)
        const tx = testTxBuilder
          .provide(sendableUtxo)
          .weiPerByte(this.weiPrice)
          .sendEther({
            eth: Sum.from([sendableUtxo]).eth.div(new BN(2)), // TODO: reduce amount as much as a half of fee
            salt: sendableUtxo.salt.muln(2),
            to: this.account?.zkAddress!,
          })
          .build()

        const parsedZkTx = {
          inflow: tx.inflow.map(flow => {
            return {
              hash: flow.hash().toString(),
              salt: flow.salt.toString(10),
              eth: flow.eth().toString(10),
            }
          }),
          outflow: tx.outflow.map(flow => {
            return {
              hash: flow.hash().toString(),
              salt: flow.salt.toString(10),
              eth: flow.eth().toString(10),
            }
          }),
        }
        logger.info(`Created ZkTx : ${logAll(parsedZkTx)}`)
        try {
          await this.sendTx({
            tx,
            from: this.account,
            encryptTo: this.account?.zkAddress,
          })
          this.usedUtxoSalt.add(sendableUtxo.salt.toNumber())
        } catch (err) {
          logger.error(err)
        }
      } else {
        logger.debug(`No available utxo for now wait 1 sec`)
      }
      await sleep(1000)
    }
  }

  stopGenerator() {
    this.isActive = false
  }
}
